**Current situation:**

* It's just working for W5,W6,W7,W8 for now.



**Next steps:** 

* Code will change other weights values
* Short and fast code as possible as it can

![alt text](https://files.slack.com/files-pri/TJ4HDSV9D-FJEN83421/ekran_resmi_2019-05-05_21.18.54.jpg)

In [0]:
import numpy as np
b1,b2=.35,.60
hedef=np.array([[.01,.99]], dtype=np.float64)
def sigmoid_fonk(x):
  return (1/(1+np.exp(-x)))
girdiler=np.array([[.05,.10]])
agirliklar_1=np.array([[.15,.25],
                       [.20,.30]], dtype=np.float64)
agirliklar_2=np.array([[.40,.50],
                       [.45,.55]], dtype=np.float64)
#iterasyon sayısı belirlenecek for döngüsü yeri - iteration number for loop
for level in range(0,100000):
  h1h2_out=sigmoid_fonk(np.dot(girdiler,agirliklar_1)+b1) #İleri besleme hesaplaması ORTA KATMAN - HIDDEN LAYER
  o1o2_out=sigmoid_fonk(np.dot(h1h2_out,agirliklar_2)+b2) #İleri besleme hesaplaması ÇIKIŞ - OUT
  hata_o1o2=((hedef-o1o2_out)**2)/2
  #toplamhata=np.sum(hata_o1o2)
  #o1 o2 için w5,w6,w7,w8 belirleme döngüsü yeri
  for i in range(0,2):
    hata1=(-1)*(hedef[0,i]-o1o2_out[0,i])  #out o1 e göre türev ---> hedef_o1 - out_o1
    hata2=o1o2_out[0,i]*(1-o1o2_out[0,i]) #net o1 e gore türev sigmoid türevi---> out_o1*(1-out_o1) ---< sigmoid function derivative
    for j in range(0,2):
      hata3=h1h2_out[0,j] #w5 e göre türev --> out h1 , w6 için out h2
      sonhata=hata1*hata2*hata3
      agirliklar_2[j,i]=agirliklar_2[j,i]-0.5*sonhata # i--> w5,w6 dan w7,w8 e geçiş için o1 ve o2 ye göre
print("\tAgirliklar:\n",agirliklar_2)
print("\tHata:\n",hata_o1o2)
print("\tO1_O2:\n ",o1o2_out)

	Agirliklar:
 [[-4.36550232  3.31306866]
 [-4.34453525  3.38020676]]
	Hata:
 [[7.15647886e-09 7.12046873e-09]]
	O1_O2:
  [[0.01011964 0.98988066]]
