**PyTorch da Matris işlemleri Numpy kütüphanesi gibi ve çok benzerler**

In [0]:
import torch
import numpy as np

**Rastgele Sayılardan Oluşan Matris**

In [21]:
rastgele=torch.rand(4,4)
print(rastgele)

tensor([[0.5045, 0.7049, 0.7944, 0.1627],
        [0.9287, 0.1695, 0.3122, 0.2338],
        [0.1907, 0.0253, 0.6011, 0.3051],
        [0.6779, 0.2653, 0.6725, 0.1408]])


**Birlerden oluşan Matris oluşturma**

**Aynı zamanda numpy'da olduğu gibi tip belirlemesi yapabiliyoruz.**

In [22]:
bir=torch.ones(4,4,dtype=torch.int)
print(bir)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


**Matrisin Boyutlarını Öğrenme**

In [23]:
print(bir.shape)
print(rastgele.size())

torch.Size([4, 4])
torch.Size([4, 4])


**Matrisi yeniden boyutlandırma**

In [26]:
bir=bir.view(16)
rastgele=rastgele.view(2,8)
print(bir.shape)
print(rastgele.shape)

torch.Size([16])
torch.Size([2, 8])


**Fonksiyonun sonuna "_" ekleyerek matrisi tekrar kendisine eşitlemeden matrise ekleme çıkarma vs.yapabiliriz.**

In [34]:
rastgele_2=torch.ones(3,2)
rastgele_2

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [35]:
rastgele_2.add(6) #Rastgele_2 yi değiştirmiyor.
print(rastgele_2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [36]:
rastgele_2.add_(6) #Rastgele_2 yi değiştiriyor.
print(rastgele_2)

tensor([[7., 7.],
        [7., 7.],
        [7., 7.]])


**Numpy'dan Tensor'a <----> Tensor'dan Numpy'a**

In [76]:
numpyx=np.zeros((3,2))
numpyx

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [77]:
tensorx=torch.from_numpy(numpyx)
tensorx

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [78]:
numpyx=tensorx.numpy()
numpyx

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

**Dikkat edilmesi nokta birbirine çevirdiğimiz numpy ve tensor aynı belleği paylaşıyorlar. Yani birini değiştirdiğimizde diğeri de değişiyor.**

In [79]:
tensorx.add_(5)
tensorx

tensor([[5., 5.],
        [5., 5.],
        [5., 5.]], dtype=torch.float64)

In [80]:
numpyx

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

**Numpy değiştirdiğimizde Tensor değişmiyor.**

In [81]:
numpyx=numpyx*5
numpyx

array([[25., 25.],
       [25., 25.],
       [25., 25.]])

In [82]:
tensorx

tensor([[5., 5.],
        [5., 5.],
        [5., 5.]], dtype=torch.float64)